### ISSUE TITLE
Exclude the tekton based resources from argocd 

### ISSUE THREAD

**Issue by harshad16** [operate-first/argocd-apps#65]
The tekton pipelinerun and taskrun are to be excluded from the argocd resources. As these contents are generated dynamically, these resources would explode tekton based application on argocd deployment.  
```
- apiGroups:
  - "tekton.dev"
  kinds:
  - "PipelineRun"
  - "TaskRun"
  clusters:
  - "*"
```
